version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - with_teacher_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - with_teacher_static:/data/static/
      - with_teacher_media:/data/media/
      - with_teacher_log:/var/log/nginx/
    secrets:
      - NGINX_AUTH

  goaccess:
    image: allinurl/goaccess:1.5.1
    ports:
      - 7890:7890
    volumes:
      - with_teacher_log:/var/log/nginx/
    command: /var/log/nginx/with_teacher_access.log -o /var/log/nginx/report.html --real-time-html --log-format COMBINED

  django:
    image: with_teacher_django:5
    networks:
      - with_teacher_network
    volumes:
      - with_teacher_static:/home/with_teacher/staticfiles/
      - with_teacher_media:/home/with_teacher/media/
    secrets:
      - DjangoSecretKey
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - with_teacher_network
    volumes:
      - with_teacher_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  with_teacher_network:

volumes: #자동으로 만들기 가능
  with_teacher_static:
  with_teacher_media:
  with_teacher_mariadb:
  with_teacher_log:

secrets: #지정 필수
  DjangoSecretKey:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true